/*
 * Copyright (c) 2010, Oracle. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Oracle nor the names of its contributors
 *   may be used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

package examples;

import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;

public class DoctorFrame extends javax.swing.JFrame {
    
    /** Creates new form DoctorFrame */
    public DoctorFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        manageAccountBtn = new javax.swing.JButton();
        acceptBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        waitingListTable = new javax.swing.JTable();
        viewMoreInformationBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();
        markAsTreatedBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Antenna");

        manageAccountBtn.setText("Manage Account");
        manageAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountBtnActionPerformed(evt);
            }
        });

        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        waitingListTable.setAutoCreateRowSorter(true);
        waitingListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Steve",  new Double(6.5), "Not Accepted"},
                {"Linda",  new Double(2.2), "Not Accepted"},
                {"Sona",  new Double(5.6), "Not Accepted"},
                {"John",  new Double(5.4), "Not Accepted"}
            },
            new String [] {
                "Name", "Average Pain Level", "Acceptance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        waitingListTable.setName(""); // NOI18N
        waitingListTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(waitingListTable);
        if (waitingListTable.getColumnModel().getColumnCount() > 0) {
            waitingListTable.getColumnModel().getColumn(0).setResizable(false);
            waitingListTable.getColumnModel().getColumn(1).setResizable(false);
            waitingListTable.getColumnModel().getColumn(2).setResizable(false);
        }

        viewMoreInformationBtn.setText("View More Information");
        viewMoreInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoreInformationBtnActionPerformed(evt);
            }
        });

        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBtnActionPerformed(evt);
            }
        });

        markAsTreatedBtn.setText("Mark as Treated");
        markAsTreatedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAsTreatedBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh List");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(manageAccountBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(acceptBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rejectBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(viewMoreInformationBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(markAsTreatedBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(refreshBtn))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 663, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, manageAccountBtn)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, acceptBtn)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, rejectBtn)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, viewMoreInformationBtn)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, refreshBtn)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, markAsTreatedBtn))
                .add(34, 34, 34))
        );

        pack();
    }// </editor-fold>                        

    private void manageAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // Display Manage Account information
        ContactEditor edit = new ContactEditor();
        edit.setVisible(true);
    }                                                

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Reject Patient and move them off the doctor's personal list
        
        DefaultTableModel model = (DefaultTableModel) waitingListTable.getModel();
        model.removeRow(waitingListTable.getSelectedRow());
    }                                         

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Mark Patient as Accepted 
        waitingListTable.setValueAt("Accepted", waitingListTable.getSelectedRow(), 2);
    }                                         

    private void viewMoreInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // View Detailed Patient Information
        Find find = new Find();
        find.setVisible(true);
    }                                                      

    private void markAsTreatedBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // Removes Patient From List
        DefaultTableModel model = (DefaultTableModel) waitingListTable.getModel();
        model.removeRow(waitingListTable.getSelectedRow());
    }                                                

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antenna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antenna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antenna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antenna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antenna().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton acceptBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageAccountBtn;
    private javax.swing.JButton markAsTreatedBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JButton viewMoreInformationBtn;
    private javax.swing.JTable waitingListTable;
    // End of variables declaration                   
    
}
